POST https://nodejs-practice-rocketseat.onrender.com/videos
Content-Type: application/json

{
  "title": "Video 04",
  "description": "Esse é o video 04",
  "duration": 180
}

###

GET https://nodejs-practice-rocketseat.onrender.com/videos?search=video

###

PUT https://nodejs-practice-rocketseat.onrender.com/videos/45dc7ce5-e7ce-493b-9cb8-dc1b1c64d060
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o video 02",
  "duration": 190
}

###

DELETE https://nodejs-practice-rocketseat.onrender.com/videos/45dc7ce5-e7ce-493b-9cb8-dc1b1c64d060
